# Generated by Django 2.2.4 on 2024-08-09 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_exam', '0002_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='uploaded_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ideas_uploaded', to='app_exam.User'),
            preserve_default=False,
        ),
    ]
