# Generated by Django 2.2.4 on 2024-08-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_exam', '0005_auto_20240809_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='uploaded_by',
            new_name='user',
        ),
    ]
