# Generated by Django 2.2.4 on 2024-08-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_exam', '0006_auto_20240809_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='updated_at',
        ),
    ]
